services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
#        bind:
#            $apiDriver: '%sfs_translatable.api.driver%'

    Softspring\TranslatableBundle\Controller\TranslatorController: ~

    Softspring\TranslatableBundle\Twig\Extension\TranslatorExtension:
        tags: [ 'twig.extension' ]