services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $apiDriver: '%sfs_translatable.api.driver%'

    Softspring\TranslatableBundle\Twig\Extension\TranslatorExtension:
        tags: [ 'twig.extension' ]

    Softspring\TranslatableBundle\Doctrine\TranslationFieldListener:
        tags:
            - { name: doctrine.event_listener, event: postLoad }