services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Google\Cloud\Translate\V2\TranslateClient: ~

    Softspring\TranslatableBundle\Api\Driver\GoogleTranslatorDriver:
        arguments:
            $client: '@Google\Cloud\Translate\V2\TranslateClient'

    Softspring\TranslatableBundle\Api\Driver\TranslatorDriverInterface:
        alias: Softspring\TranslatableBundle\Api\Driver\GoogleTranslatorDriver

